name: Build ARM32 Linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake pkg-config libwayland-dev libx11-dev libxkbcommon-dev libgles2-mesa-dev zip curl

      - name: Download Specific Flutter 3.41.2
        run: |
          cd $HOME
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.41.2-stable.tar.xz
          tar xf flutter_linux_3.41.2-stable.tar.xz
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Fresh Version
        run: |
          # This should now show 3.41.2 and Dart 3.11+
          flutter --version

      - name: Setup Sony Tool
        run: |
          git clone https://github.com/sony/flutter-elinux.git
          echo "$GITHUB_WORKSPACE/flutter-elinux/bin" >> $GITHUB_PATH

      - name: Build for ARM32
        run: |
          cd my_app
          flutter-elinux create .
          flutter-elinux pub get
          flutter-elinux build elinux --target-arch=arm --target-backend-type=x11 --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm32-app
          path: my_app/build/elinux/arm/release/bundle/
